#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

stemcell=$( basename "$PWD" )

weight=regular

if [[ "$stemcell" =~ -light$ ]]; then
  weight=light
  stemcell=$( echo "$stemcell" | sed 's/-light$//' )
fi

raw=$( wget -qO- "https://bosh.io/api/v1/stemcells/$stemcell" )

if [ -n "${version_series:-}" ]; then
  raw="$( echo "$raw" | jq -r --arg series "$version_series" 'map(select(.version | split(".")[0] == $series))' )"
fi

if [ -z "${version:-}" ]; then
  version=$( echo "$raw" | jq -r --arg weight "$weight" 'map(select(.[$weight]))[0].version' )
fi

json=$( echo "$raw" | jq --arg version "$version" --arg weight "$weight" -r 'map(select(.version == $version))[0][$weight]' )

url=$( echo "$json" | jq -r .url )
name=$( basename "$url" )
size=$( echo "$json" | jq -r .size )
sha1=$( echo "$json" | jq -r .sha1 )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="${name}">
    <hash type="sha-1">${sha1}</hash>
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
