#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    curl -s -l \
      ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/ \
      | grep -E '^pcre-.+.tar.gz$' \
      | sed -E 's/^pcre-(.+)\.tar.gz$/\1/' \
      | gsort -rV \
      | head -n1
  )
fi

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="pcre-${version}.tar.gz">
    <url>ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${version}.tar.gz</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
