#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

repo=$( basename "$( dirname "$( dirname "$PWD" )" )" )/$( basename "$( dirname "$PWD" )" )/$( basename "$PWD" )
json=$(
  wget -qO- "https://bosh.io/api/v1/releases/$repo" \
    | jq '.[0]'
)

version=$( echo "$json" | jq -r .version )
url=$( echo "$json" | jq -r .url )
sha1=$( echo "$json" | jq -r .sha1 )
filename=$( basename "$repo" )-$version.tgz

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="${filename}">
    <hash type="sha-1">${sha1}</hash>
    <url>${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
