#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

plugin=$( basename "$PWD" )

if [ -z "${version:-}" ]; then
  version=$(
    wget -qO- "https://api.wordpress.org/plugins/info/1.0/$plugin.json" \
      | jq -r .version
  )
fi

url=http://downloads.wordpress.org/plugin/${plugin}.${version}.zip
size=$( curl -sLI "$url" | grep Content-Length | tail -n1 | awk '{ print $2 }' | tr -cd '[:digit:]' )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="${plugin}.${version}.zip">
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
