#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    git ls-remote --tags https://github.com/WordPress/WordPress.git \
      | cut -f2 \
      | grep -E '^refs/tags/.+$' \
      | sed -E 's/^refs\/tags\/(.+)$/\1/' \
      | gsort -rV \
      | head -n1 \
  )
fi

url=https://downloads.wordpress.org/release/wordpress-${version}.tar.gz
size=$( curl -sI "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )

sha1=$( wget -qO- "https://wordpress.org/wordpress-${version}.tar.gz.sha1" )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="wordpress-${version}.tar.gz">
    <hash type="sha-1">${sha1}</hash>
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
