#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

plugin=$( basename "$PWD" )
json=$(
  wget -qO- "https://bosh.io/api/v1/stemcells/$plugin" \
    | jq '.[0]'
)

version=$( echo "$json" | jq -r .version )
url=$( echo "$json" | jq -r .light.url )
sha1=$( echo "$json" | jq -r .light.sha1 )
filename=$( basename "$url" )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="${filename}">
    <hash type="sha-1">${sha1}</hash>
    <url>${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
