#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  # https does not seem to work from the concourse worker (403 Forbidden)
  version=$(
    wget -qO- http://www.oberhumer.com/opensource/lzo/download/ \
      | grep -E 'href="lzo-[^"]+.tar.gz"' \
      | sed -E 's/^.+href="lzo-([^"]+).tar.gz".+$/\1/' \
      | sort -rV \
      | head -n1
  )
fi

url=https://www.oberhumer.com/opensource/lzo/download/lzo-${version}.tar.gz
size=$( curl -sLI "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )

sha1=$(
  wget -qO- http://www.oberhumer.com/opensource/lzo/ \
    | grep -E 'SHA1: ' \
    | sed -E 's/.+SHA1: +([a-f0-9]+).+/\1/' \
    | head -n1
)

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="lzo-${version}.tar.gz">
    <hash type="sha-1">${sha1}</hash>
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
