#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    git ls-remote --tags https://github.com/openssl/openssl.git \
      | cut -f2 \
      | grep -v '\^{}' \
      | grep -E '^refs/tags/OpenSSL_.+$' \
      | sed -E 's/^refs\/tags\/OpenSSL_(.+)$/\1/' \
      | tr '_' '.' \
      | sort -rV \
      | grep -E '^\d+\.\d+\.\d+\w?$' \
      | head -n1
  )
fi

url=https://www.openssl.org/source/openssl-${version}.tar.gz
size=$( curl -sLI "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )

sha1=$( wget -qO- "https://www.openssl.org/source/openssl-${version}.tar.gz.sha1" || true )
sha256=$( wget -qO- "https://www.openssl.org/source/openssl-${version}.tar.gz.sha256" || true )
signature=$( wget -qO- "https://www.openssl.org/source/openssl-${version}.tar.gz.asc" )

if [ -z "$sha256" ]; then
  hash_type=sha-1
  hash_value=$sha1
else
  hash_type=sha-256
  hash_value=$sha256
fi

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="openssl-${version}.tar.gz">
    <hash type="${hash_type}">${hash_value}</hash>
    <signature mediatype="application/pgp-signature">${signature}</signature>
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
