#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

origin="$1"
repository="$2"

cd "$repository"
repository_dir="$PWD"

echo "$repository"

rm -fr /tmp/ubr-watch
mkdir /tmp/ubr-watch

./.latest > /tmp/ubr-watch/metalink.meta4

cd /tmp/ubr-watch

version=$( meta4 file-version )
filename=$( meta4 files )
metalink="v$version.json"

if [ -e "$repository_dir/$metalink" ]; then
  exit
fi

# download
aria2c metalink.meta4

# remove the original url
meta4 file-remove-url "$( meta4 file-urls )"

# import more details
meta4 import-file --merge "$filename"

# upload
sha1=$( meta4 file-hash sha-1 )
meta4 file-upload "$filename" "$origin$sha1"

cp metalink.meta4 "$repository_dir/$metalink"

rm -fr /tmp/ubr-watch
