#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

raw=$( wget -qO- 'https://secure.php.net/releases/index.php?json&max=128&version=5' )

if [ -z "${version:-}" ]; then
  version=$( echo "$raw" | jq -r 'to_entries[0].key' )
fi

json=$( echo "$raw" | jq --arg version "$version" -r '.[$version].source | map(select(.filename | test("\\.tar\\.gz$") ))[0]' )

filename=$( echo "$json" | jq -r .filename )
sha256=$( echo "$json" | jq -r .sha256 )
md5=$( echo "$json" | jq -r .md5 )

if [ -z "$sha256" ]; then
  hash_type=sha-256
  hash_value=$sha256
else
  hash_type=md5
  hash_value=$md5
fi

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="php-${version}.tar.gz">
    <hash type="${hash_type}">${hash_value}</hash>
    <url>http://us1.php.net/distributions/php-${version}.tar.gz</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
