#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    git ls-remote --tags https://github.com/git/git.git \
      | cut -f2 \
      | grep -v '\^{}' \
      | grep -E '^refs/tags/v.+$' \
      | sed -E 's/^refs\/tags\/v(.+)$/\1/' \
      | grep -v -- - \
      | sort -rV \
      | head -n1
  )
fi

url=https://www.kernel.org/pub/software/scm/git/git-${version}.tar.gz
size=$( curl -sLI "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )

sha256=$(
  wget -qO- "https://www.kernel.org/pub/software/scm/git/sha256sums.asc" \
    | grep "git-${version}.tar.gz" \
    | awk '{ print $1 }'
)

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="git-${version}.tar.gz">
    <hash type="sha-256">${sha256}</hash>
    <size>${size}</size>
    <url priority="1000">${url}</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
