---
jobs:
- name: update
  plan:
  - get: repo
  - get: trigger
    trigger: true
  - task: update
    file: repo/tasks/update/config.yml
    params:
      AWS_ACCESS_KEY_ID: ((aws_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
      S3_BLOBS: ((s3_blobs))
      S3_REPOS_BUCKET: ((s3_repos_bucket))
      GIT_AUTHOR_EMAIL: Concourse
      GIT_AUTHOR_NAME: concourse@localhost
  - put: repo
    params:
      repository: repo
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:dpb587/upstream-blob-mirror.git
    branch: master
    private_key: ((git_private_key))
- name: trigger
  type: time
  source:
    interval: 12h
