#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    git ls-remote --tags https://github.com/OpenVPN/openvpn.git \
      | cut -f2 \
      | grep -Ev '\^\{\}' \
      | grep -E '^refs/tags/v.+$' \
      | sed -E 's/^refs\/tags\/v(.+)$/\1/' \
      | tr '_' '.' \
      | grep -E '^\d+\.\d+\.\d+$' \
      | gsort -rV \
      | head -n1
  )
fi

signature=$( wget -qO- "https://swupdate.openvpn.org/community/releases/openvpn-${version}.tar.gz.asc" )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="openvpn-${version}.tar.gz">
    <signature mediatype="application/pgp-signature">${signature}</signature>
    <url priority="1000">https://swupdate.openvpn.org/community/releases/openvpn-${version}.tar.gz</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
