#!/bin/bash

set -eu -o pipefail ; export SHELLOPTS

if [ -z "${version:-}" ]; then
  version=$(
    git ls-remote --tags https://github.com/openssl/openssl.git \
      | cut -f2 \
      | grep -Ev '\^{}' \
      | grep -E '^refs/tags/OpenSSL_.+$' \
      | sed -E 's/^refs\/tags\/OpenSSL_(.+)$/\1/' \
      | tr '_' '.' \
      | gsort -rV \
      | grep -E '^\d+\.\d+\.\d+\w?$' \
      | head -n1
  )
fi

sha256=$( wget -qO- "https://www.openssl.org/source/openssl-${version}.tar.gz.sha256" )

cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="openssl-${version}.tar.gz">
    <hash type="sha-256">${sha256}</hash>
    <url>https://www.openssl.org/source/openssl-${version}.tar.gz</url>
    <version>${version}</version>
  </file>
</metalink>
EOF
